# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: nord
  theme_night: nord
  font: roboto
  font_size: M

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: 'Non-Profit'
    org_name: 'IFIPTM'
    description: 'IFIP Working Group 11.11 on Trust Management'
    twitter: 'ifiptm'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  copyright:
    notice: '© {year} IFIP Working Group 11.11 Trust Management.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'January 2, 2006'
  time_format: '15:04'
  address_format: en-ca

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
      - c
      - rust
      - cpp
      - java
      - javascript
  math:
    enable: true
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/ifiptm/ifiptm.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
